# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:ZMZ Theme # ex. I am Zhao Mingzhe
name: Your Name # ex. Zhao Mingzhe
email: my_email_address@lalala.com
location: My location # ex. Nanjing, China
company: MyCompany
company_url: my_company_website
github_url: my_github_url # ex. https://github.com/zmz-nuaa
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: github_username/github_username.github.io # ex. zmz-nuaa/zmz-nuaa.github.io
# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: http://localhost:4000
theme: jekyll-theme-cayman